---

coverage:
  range: 20..60
  round: down
  precision: 2
  status:
    project:
      default:
        target: 25%
        threshold: 10%
    patch:
      default:
        target: 10%
        threshold: 10%
